### ISSUE TITLE
Wonderful work!

### ISSUE THREAD

**Issue by it33** [mtorromeo/mattersend#1]
Hi @mtorromeo, thanks for building this! 

We'd love to promote it, would you be open to [sharing some details](https://twitter.com/pypi_updates/status/695621152690065408)? 

Would love to send you a modest thank-you gift as well!

**Comment by mtorromeo** [comment]
@it33 Thanks!
I'm glad you like it, and thanks for building mattermost.
What kind of details would you like to know about?
PS: I love gifts :smile:

**Comment by it33** [comment]
If you click the link above it'll have a form where we can info on release date, URL, etc. it feeds into a process where links are added to mattermost.org. You also enter your address so we know where to send the gift :)

**Comment by mtorromeo** [comment]
The link points to a twitter post. Am I missing something?

**Comment by it33** [comment]
Whoops! Sorry, should be this: https://spinpunch.wufoo.com/forms/mattermost-integrations-and-installers/

**Comment by mtorromeo** [comment]
All done!
