### ISSUE TITLE
Dependencies incomplete

### ISSUE THREAD

**Issue by sedrubal** [mtorromeo/mattersend#2]
configparser and pathlib are not installed automatically. Can you add them to setup.py as dependency?

**Comment by mtorromeo** [comment]
Actually, they are both part of python's standard library from python 3.4 which is the required version advertised in setup.py.

I was planning on supporting older python versions though so I am going to look into it next.

**Comment by sedrubal** [comment]
Ah sorry, I used python2... But normally it shouldn't be as hard to support 2 and 3... Thanks ;)

**Comment by mtorromeo** [comment]
Current git version supports python 2. You can give it a try if you want.
