### ISSUE TITLE
icon does not work

### ISSUE THREAD

**Issue by jerlich** [mtorromeo/mattersend#4]
I get the broken images or default icons when specifying the icon.

**Comment by mtorromeo** [comment]
Apparently mattermost changed the url for the files from their emoji names to their unicode codes.
Eg. `/static/images/emoji/confounded.png` is now `/static/emoji/1f616.png`

I'll have to use a translation table to support the new scheme.

**Comment by jerlich** [comment]
in my installation they are in `/opt/mattermost/webapp/dist/emoji`

**Comment by mtorromeo** [comment]
Yes, the `dist/` directory becomes `static/` in public URLs and they also moved `images/emoji/` to just `emoji/`, but the most problematic change remains the renaming of the images themselves.

**Comment by jerlich** [comment]
I realized that dist becomes static, so i deleted my comment.  I did a little digging and the map is in 
`main.XXX.js` (not sure if that middle XXX part matters or is a hash, so i excluded it here.).
