### ISSUE TITLE
Send rich formatted attachments?

### ISSUE THREAD

**Issue by stobias123** [mtorromeo/mattersend#6]
I'm trying to send a richly formatted attachment. Is there any way I can directly pass a .json file or string into the script? I tried with the -f argument and also tried `cat test.json | mattersend` to no avail.

**Comment by mtorromeo** [comment]
What do you mean? Is it not working at all or are you referring to missing syntax highlight in mattermost?

For the latter case you just have to specify the syntax on the command line with `-y` like this:
```bash
cat test.json | mattersend -y json
```

It should be detected automatically from the filename if you use `-f` though...

**Comment by mtorromeo** [comment]
Are you maybe trying to DM yourself? Mattermost does not support that and you would get a `Couldn't find the channel (500)` error message.
You can vote for that feature to be implemented here: https://mattermost.uservoice.com/forums/306457-general/suggestions/15697014-add-option-to-direct-message-yourself

**Comment by stobias123** [comment]
I should have phrased better. I meant "attachments". Ex. I want to make a red/green header, or include fields.
https://docs.mattermost.com/developer/message-attachments.html

**Comment by mtorromeo** [comment]
So your test.json file would contain the raw attachment data?
Something like this?
```json
{
  "attachments": [
    {
      "fallback": "test",
      "color": "#FF8000",
      "pretext": "This is optional pretext that shows above the attachment.",
      "text": "This is the text of th..."
    }
  ]
}
```

If this is the case curl would be a better tool for the job: `curl -XPOST https://WEBHOOKURL -d@test.json`

If instead you are asking for a way to specify something like `mattersend --fallback test --color "#FF8000" --pretext "This is optional pretext that shows above the attachment." --text "This is the text of th..."` then this is not supported yet and I still need to decide what would be a good CLI interface to handle an arbitrary number of attachments and fields without having an insane number of arguments.

If I find some time this weekend I'll try to come up with a solution for this use case.

**Comment by stobias123** [comment]
Yes that's the use case.

I'll just run with curl then. Thanks!
